In [2]:
import numpy as np

l1=[2,3,5,6,3,6,4,4,3]
np.array(l1)
arr=np.array(l1)
print(arr)
type(arr)


[2 3 5 6 3 6 4 4 3]


numpy.ndarray

In [3]:
li2=[4,2,6,5,3,5,5,3]
li3=[3,6,3,7,3,4,5,5]
np.array([li2,li3])

array([[4, 2, 6, 5, 3, 5, 5, 3],
       [3, 6, 3, 7, 3, 4, 5, 5]])

In [4]:
a=[2,4,67,8,9]
b=[2,5,7,45,9]
c=[4,5,7,23,6]
np.array([a,b,c])
arr1=np.array([a,b,c])
arr1.shape


(3, 5)

In [5]:
arr1=np.array([a,b,c])
arr1.shape



(3, 5)

In [6]:
#indexing
arr1

arr1[:,1]
arr1[:1,:3]
arr1[2:,2:5]

array([[ 7, 23,  6]])

In [7]:
arr1=np.array([a,b,c])
arr

array([2, 3, 5, 6, 3, 6, 4, 4, 3])

In [8]:
arr1[:1,:3]

array([[ 2,  4, 67]])

In [9]:
arr
arr2=np.arange(0,18,2)
arr2
print(arr2)

[ 0  2  4  6  8 10 12 14 16]


In [10]:
arr
s=arr *arr2
print(s)


[ 0  6 20 36 24 60 48 56 48]


In [11]:
# array of ones and zeroes
print(np.ones((4,5)))
print(np.zeros((4,5)))


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
arr

array([2, 3, 5, 6, 3, 6, 4, 4, 3])

In [16]:
np.random.randint(4,10,3)

array([7, 8, 9])