numpy is the fundamental pcakage for the scientific computating in python 
python provide multidimensional arrray object   --> various derived onject such as marked array and metrics 
important points
numpy arrays have a fixed size at creation unlike python lists (which grow dynamiclaly changing the size of an ndarray will create a new array and delete the original)

In [1]:
import numpy as np

#creating the numpy array 
#there are many ways to create numpy array
    #1. using np.array() function
    #2. using np.zeros() function
    #3. using np.ones() function
    #4. using np.arange() function
    #5. using np.array() function




In [2]:
#1. using np.array() function
#one dimensional array 
l1=[2,3,5,6,3,6,4,4,3]
arr=np.array(l1)
print(arr)
type(arr)

[2 3 5 6 3 6 4 4 3]


numpy.ndarray

In [3]:
#two dimensional array

li2=[4,2,6,5,3,5,5,3]
li3=[3,6,3,7,3,4,5,5]

arr=np.array([[2,3,4,5,6],[3,4,5,6,7]])
print(np.array([li2,li3]))
print(arr)



[[4 2 6 5 3 5 5 3]
 [3 6 3 7 3 4 5 5]]
[[2 3 4 5 6]
 [3 4 5 6 7]]


In [4]:
#3-d array 
a=[2,4,67,8,9]
b=[2,5,7,45,9]
c=[4,5,7,23,6]
print(np.array([a,b,c]))
arr1=np.array([[[2,3,4],[3,4,5],[4,5,6]],[[2,3,4],[3,4,5],[4,5,6]]])
print("the shape of the array is ",arr1.shape)
print(arr1)


[[ 2  4 67  8  9]
 [ 2  5  7 45  9]
 [ 4  5  7 23  6]]
the shape of the array is  (2, 3, 3)
[[[2 3 4]
  [3 4 5]
  [4 5 6]]

 [[2 3 4]
  [3 4 5]
  [4 5 6]]]


In [5]:
#Array of favorite data type
arr=np.array([2,3,4,5,6],dtype=float)
#by dtype we can change the data type of the array and know  the data type of the array
arr=np.array([2,3,4,5,6],dtype=bool)
print(arr)

[ True  True  True  True  True]


In [6]:
#secand function to create arrray is np.arange(start,stop,step)
arr=np.arange(1,10,2)
print(arr.shape)
#it will create the array from 1 to 10 with step of 2
#.reshape() function is used to change the shape of the array it is most of the work with the np.arange() function

arr1=np.arange(2,21,2).reshape(5,2)
print(arr1)

(5,)
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [7]:
#third function to create the array is np.zeros() function and np.ones() function
#np.zeros() function will create the array of zeros
#np.zeros_like() and np.ones_like() function will create the array of zeros and ones like the given array
arr=np.zeros(5)
print(arr)

arr=np.zeros((3,3))
#used to initialize the array with zeros
print(arr)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#np.ones(tuple) it take arugument as tuple and create the array of ones
arr=np.ones((3,3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#there is  one more function is by random method 
#np.random.rand() function is used to create the array of random numbers
arr=np.random.rand(3,3)
print("array of natural numbers ",arr)
#np.random.randint() function is used to create the array of random integers
arr=np.random.randint(1,10,(3,3)) # randint(start,stop,(shape))

print(arr)

#np.random.randn() function is used to create the array of random numbers with normal distribution
arr=np.random.randn(3,3)
#rint(arr)
#np.random.normal() function is used to create the array of random numbers with normal distribution
#np.randon.random() function is used to create the array of random numbers between 0 and 1
arr=np.random.random((3,3))
print(arr)

array of natural numbers  [[0.97628163 0.76445197 0.03864138]
 [0.01907013 0.95236166 0.19668395]
 [0.29856056 0.62477452 0.34074294]]
[[9 8 5]
 [1 5 1]
 [3 7 5]]
[[0.10256222 0.71165434 0.55268272]
 [0.98550181 0.80586659 0.97012513]
 [0.61521271 0.13729405 0.16648545]]


In [13]:
# THIRD METHOD IS  LINEARLY SEPARABLE 
#np.linspace(start,stop,NO OF number) function is used to create the array of linearly separable numbers
# give the start and stop and the number of numbers you want between the start and stop the number is equally spaced means the distance between the two numbers is same
arr=np.linspace(1,10,5)

arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
#np.eye() function is used to create the identity matrix also called as unit matrix
#np.indentity() function is also used to create the identity matrix
arr=np.eye(3)
print(arr)
arr=np.identity(3)
print(arr)
#create a matrix of 3*3 with diagonal elements as 1 and rest of the elements as 0

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


there are all the methods to create a numpy array 



In [21]:
#Arra attribues
#1. shape
a1=np.arange(12)
print(a1.reshape(3,4))
print("shape is ",a1.shape)

#2. size
print("item size is ",a1.size)

#3. ndim
print("dimension",a1.ndim)

#4. dtype
print("data type is ",a1.dtype)

#5. itemsize
print("item size is",a1.itemsize)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape is  (12,)
item size is  12
dimension 1
data type is  int32
item size is 4


In [24]:
#changing data type of the array
a1=np.arange(12)
print(a1)
print(a1.dtype)
a1=a1.astype(float)

#also change to the int 32 ,int64 and so on 
print(a1.astype(np.int32))
print(a1.dtype)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
int32
[ 0  1  2  3  4  5  6  7  8  9 10 11]
float64


In [11]:
arr

array([2, 3, 5, 6, 3, 6, 4, 4, 3])

In [12]:
np.random.randint(4,10,3)

array([7, 5, 8])

#Okay, here's an improved and consolidated guide to the essential NumPy functions, focusing on practical application, syntax, and key concepts, drawing from the sources and our conversation history:

**Core NumPy Functions for Practical Use**

This section details the most useful NumPy functions, their syntax, and how they're applied in real-world data analysis and machine learning.

*   **Array Manipulation:**

    *   **`np.sort()`**: Sorts array elements.
        *   **Syntax:**
            *   `np.sort(array)`: Sorts a 1D array in ascending order.
            *   `np.sort(array, axis=0)`: Sorts a 2D array column-wise.
            *   `np.sort(array, axis=1)`: Sorts a 2D array row-wise.
            *   `np.sort(array, kind='quicksort')`: Specifies the sorting algorithm (e.g., quicksort).
        *   **Key points:** Returns a *sorted copy* of the array; the original array is unchanged. Use the `axis` parameter for multidimensional sorting.
    *   **`np.append()`**: Adds items to the end of an array.
        *   **Syntax:**
            *  `np.append(array, values)`: Appends `values` to the end of the flattened array.
            *   `np.append(array, values, axis=1)`: Appends `values` as a new column.
        *  **Key points**: Use the `axis` parameter to control whether you're adding to rows or columns.
    *   **`np.concatenate()`**: Joins arrays together.
        *   **Syntax:**
            *   `np.concatenate((array1, array2), axis=0)`: Concatenates arrays row-wise (vertically).
            *   `np.concatenate((array1, array2), axis=1)`: Concatenates arrays column-wise (horizontally).
        *   **Key points:** Can be used as a replacement for `vstack` and `hstack`. `axis` specifies the direction of concatenation.

*   **Data Analysis:**

    *   **`np.unique()`**: Extracts unique values from an array.
        *   **Syntax:** `np.unique(array)`
        *   **Key points:** Useful for finding distinct values within a dataset.
    *   **`np.expand_dims()`**: Adds extra dimensions to an array.
        *   **Syntax:**
            *   `np.expand_dims(array, axis=0)`: Adds a new dimension, creating a row vector.
            *   `np.expand_dims(array, axis=1)`: Adds a new dimension, creating a column vector.
         *  **Key points:** Essential for preparing data for machine learning, where algorithms often expect batches of inputs (2D data).
    *   **`np.where()`**: Returns indices of elements that meet a condition, or replaces values based on a condition.
        *   **Syntax:**
            *   `np.where(condition)`: Returns indices where the condition is true.
            *   `np.where(condition, value_if_true, value_if_false)`: Replaces values based on the condition.
         *   **Key points**: Powerful for conditional data manipulation and filtering.
    *   **`np.argmax()` and `np.argmin()`**: Finds the indices of maximum and minimum values.
        *   **Syntax:**
            *   `np.argmax(array)`: Returns the index of the maximum value in a flattened array.
            *  `np.argmax(array, axis=0)`: Returns the indices of the maximum values along each column of a 2D array.
            *   `np.argmin(array)`: Returns the index of the minimum value in a flattened array.
        *  **Key points:** Useful for quickly identifying extreme values in data.
    *   **`np.cumsum()` and `np.cumprod()`**: Calculates cumulative sum and product.
        *   **Syntax:**
            *   `np.cumsum(array)`: Cumulative sum of the flattened array.
            *   `np.cumsum(array, axis=0)`: Cumulative sum along columns.
            *  `np.cumprod(array)`: Cumulative product of the flattened array.
        *   **Key points**:  Used for tracking running totals in data analysis.
    *   **`np.percentile()`**: Computes the specified percentile of data.
        *   **Syntax:** `np.percentile(array, percentile_value)`.
        *   **Key points**: Essential for understanding data distribution and spread.
    *   **`np.histogram()`**: Calculates frequency counts within given bins (ranges).
        *   **Syntax:** `np.histogram(array, bins)`.
        *   **Key points**:  Useful for visualizing data distributions using histograms.
    *    **`np.corrcoef()`**: Calculates the Pearson correlation coefficient.
         *   **Syntax:** `np.corrcoef(array1, array2)`.
         *   **Key points**: Measures the linear relationship between two variables, from -1 to 1.

*   **Set Operations:**

    *   **`np.union1d()`, `np.intersect1d()`, `np.setdiff1d()`**: Perform set operations on arrays.
        *   **Syntax**:
            *   `np.union1d(array1, array2)`: Returns the union of the arrays.
            *   `np.intersect1d(array1, array2)`: Returns the intersection of the arrays.
            *   `np.setdiff1d(array1, array2)`: Returns the elements in `array1` that are not in `array2`.
        *   **Key points**: Similar to Python set operations, but output is a NumPy array.

*   **Other Useful Functions:**

    *   **`np.searchsorted()`**: Searches for multiple items in a sorted array.
        *   **Syntax:** `np.searchsorted(array, items_to_search)`.
        *   **Key points**: Efficient way to search for multiple items.
    *   **`np.flip()`**: Reverses the order of elements in an array.
        *   **Syntax:**
            *   `np.flip(array)`: Flips the array along all axes.
            *   `np.flip(array, axis=0)`: Flips the array along rows.
            *   `np.flip(array, axis=1)`: Flips the array along columns.
        *  **Key points**: Can reverse rows, columns, or the entire array.
    *   **`np.put()`**: Edits elements of an array at specified indices.
        *   **Syntax**: `np.put(array, indices, new_values)`.
        *    **Key points**:  Changes the original array.
    *   **`np.delete()`**: Deletes elements from an array based on their indices.
        *   **Syntax**: `np.delete(array, indices)`.
         *   **Key points**: Alters the original array.
    *   **`np.clip()`**: Limits values in an array to a specified range.
        *   **Syntax**: `np.clip(array, min_value, max_value)`.
        *    **Key points**:  Useful in machine learning and deep learning to handle outliers or ensure values are within a defined range.

**Key Concepts**

*   **Vectorization:** NumPy functions are designed to operate on entire arrays at once, not individual elements. This is much faster than using loops.
*   **Axis Parameter:** Crucial for specifying the direction of operations in multidimensional arrays (e.g., `axis=0` for columns, `axis=1` for rows).
*   **In-place vs. Copy:** Some functions (like `np.put()`, `np.delete()`) modify the original array directly, while others (like `np.sort()`) return a copy, leaving the original unchanged.

