numpy is the fundamental pcakage for the scientific computating in python 
python provide multidimensional arrray object   --> various derived onject such as marked array and metrics 
important points
numpy arrays have a fixed size at creation unlike python lists (which grow dynamiclaly changing the size of an ndarray will create a new array and delete the original)

In [ ]:
import numpy as np

#creating the numpy array 
#there are many ways to create numpy array
    #1. using np.array() function
    #2. using np.zeros() function
    #3. using np.ones() function
    #4. using np.arange() function
    #5. using np.array() function




[2 3 5 6 3 6 4 4 3]


numpy.ndarray

In [ ]:
#1. using np.array() function
#one dimensional array 
l1=[2,3,5,6,3,6,4,4,3]
arr=np.array(l1)
print(arr)
type(arr)

In [13]:
#two dimensional array

li2=[4,2,6,5,3,5,5,3]
li3=[3,6,3,7,3,4,5,5]

arr=np.array([[2,3,4,5,6],[3,4,5,6,7]])
print(np.array([li2,li3]))
print(arr)



[[4 2 6 5 3 5 5 3]
 [3 6 3 7 3 4 5 5]]
[[2 3 4 5 6]
 [3 4 5 6 7]]


In [17]:
#3-d array 
a=[2,4,67,8,9]
b=[2,5,7,45,9]
c=[4,5,7,23,6]
print(np.array([a,b,c]))
arr1=np.array([[[2,3,4],[3,4,5],[4,5,6]],[[2,3,4],[3,4,5],[4,5,6]]])
print("the shape of the array is ",arr1.shape)
print(arr1)


[[ 2  4 67  8  9]
 [ 2  5  7 45  9]
 [ 4  5  7 23  6]]
the shape of the array is  (2, 3, 3)
[[[2 3 4]
  [3 4 5]
  [4 5 6]]

 [[2 3 4]
  [3 4 5]
  [4 5 6]]]


In [19]:
#Array of favorite data type
arr=np.array([2,3,4,5,6],dtype=float)
#by dtype we can change the data type of the array and know  the data type of the array
arr=np.array([2,3,4,5,6],dtype=bool)
print(arr)

[ True  True  True  True  True]


In [25]:
#secand function to create arrray is np.arange(start,stop,step)
arr=np.arange(1,10,2)
print(arr.shape)
#it will create the array from 1 to 10 with step of 2
#.reshape() function is used to change the shape of the array it is most of the work with the np.arange() function

arr1=np.arange(2,21,2).reshape(5,2)
print(arr1)

(5,)
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [29]:
#third function to create the array is np.zeros() function and np.ones() function
#np.zeros() function will create the array of zeros
#np.zeros_like() and np.ones_like() function will create the array of zeros and ones like the given array
arr=np.zeros(5)
print(arr)

arr=np.zeros((3,3))
#used to initialize the array with zeros
print(arr)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
#np.ones(tuple) it take arugument as tuple and create the array of ones
arr=np.ones((3,3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [42]:
#there is  one more function is by random method 
#np.random.rand() function is used to create the array of random numbers
arr=np.random.rand(3,3)
print("array of natural numbers ",arr)
#np.random.randint() function is used to create the array of random integers
arr=np.random.randint(1,10,(3,3)) # randint(start,stop,(shape))

print(arr)

#np.random.randn() function is used to create the array of random numbers with normal distribution
arr=np.random.randn(3,3)
#rint(arr)
#np.random.normal() function is used to create the array of random numbers with normal distribution
#np.randon.random() function is used to create the array of random numbers between 0 and 1
arr=np.random.random((3,3))
print(arr)

array of natural numbers  [[0.66527481 0.10354915 0.17476292]
 [0.19536222 0.456251   0.43846723]
 [0.90394982 0.65150084 0.02834941]]
[[7 6 5]
 [2 5 7]
 [7 6 1]]
[[0.27605058 0.84621783 0.19213796]
 [0.33467324 0.97455979 0.67239618]
 [0.56168842 0.93734438 0.11737762]]


In [7]:
arr1[:1,:3]

array([[ 2,  4, 67]])

In [8]:
arr
arr2=np.arange(0,18,2)
arr2
print(arr2)

[ 0  2  4  6  8 10 12 14 16]


In [9]:
arr
s=arr *arr2
print(s)


[ 0  6 20 36 24 60 48 56 48]


In [10]:
# array of ones and zeroes
print(np.ones((4,5)))
print(np.zeros((4,5)))


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
arr

array([2, 3, 5, 6, 3, 6, 4, 4, 3])

In [12]:
np.random.randint(4,10,3)

array([7, 5, 8])