numpy is the fundamental pcakage for the scientific computating in python 
python provide multidimensional arrray object   --> various derived onject such as marked array and metrics 
important points
numpy arrays have a fixed size at creation unlike python lists (which grow dynamiclaly changing the size of an ndarray will create a new array and delete the original)

In [1]:
import numpy as np

#creating the numpy array 
#there are many ways to create numpy array
    #1. using np.array() function
    #2. using np.zeros() function
    #3. using np.ones() function
    #4. using np.arange() function
    #5. using np.array() function




In [2]:
#1. using np.array() function
#one dimensional array 
l1=[2,3,5,6,3,6,4,4,3]
arr=np.array(l1)
print(arr)
type(arr)

[2 3 5 6 3 6 4 4 3]


numpy.ndarray

In [3]:
#two dimensional array

li2=[4,2,6,5,3,5,5,3]
li3=[3,6,3,7,3,4,5,5]

arr=np.array([[2,3,4,5,6],[3,4,5,6,7]])
print(np.array([li2,li3]))
print(arr)



[[4 2 6 5 3 5 5 3]
 [3 6 3 7 3 4 5 5]]
[[2 3 4 5 6]
 [3 4 5 6 7]]


In [4]:
#3-d array 
a=[2,4,67,8,9]
b=[2,5,7,45,9]
c=[4,5,7,23,6]
print(np.array([a,b,c]))
arr1=np.array([[[2,3,4],[3,4,5],[4,5,6]],[[2,3,4],[3,4,5],[4,5,6]]])
print("the shape of the array is ",arr1.shape)
print(arr1)


[[ 2  4 67  8  9]
 [ 2  5  7 45  9]
 [ 4  5  7 23  6]]
the shape of the array is  (2, 3, 3)
[[[2 3 4]
  [3 4 5]
  [4 5 6]]

 [[2 3 4]
  [3 4 5]
  [4 5 6]]]


In [5]:
#Array of favorite data type
arr=np.array([2,3,4,5,6],dtype=float)
#by dtype we can change the data type of the array and know  the data type of the array
arr=np.array([2,3,4,5,6],dtype=bool)
print(arr)

[ True  True  True  True  True]


In [6]:
#secand function to create arrray is np.arange(start,stop,step)
arr=np.arange(1,10,2)
print(arr.shape)
#it will create the array from 1 to 10 with step of 2
#.reshape() function is used to change the shape of the array it is most of the work with the np.arange() function

arr1=np.arange(2,21,2).reshape(5,2)
print(arr1)

(5,)
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [7]:
#third function to create the array is np.zeros() function and np.ones() function
#np.zeros() function will create the array of zeros
#np.zeros_like() and np.ones_like() function will create the array of zeros and ones like the given array
arr=np.zeros(5)
print(arr)

arr=np.zeros((3,3))
#used to initialize the array with zeros
print(arr)


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#np.ones(tuple) it take arugument as tuple and create the array of ones
arr=np.ones((3,3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#there is  one more function is by random method 
#np.random.rand() function is used to create the array of random numbers
arr=np.random.rand(3,3)
print("array of natural numbers ",arr)
#np.random.randint() function is used to create the array of random integers
arr=np.random.randint(1,10,(3,3)) # randint(start,stop,(shape))

print(arr)

#np.random.randn() function is used to create the array of random numbers with normal distribution
arr=np.random.randn(3,3)
#rint(arr)
#np.random.normal() function is used to create the array of random numbers with normal distribution
#np.randon.random() function is used to create the array of random numbers between 0 and 1
arr=np.random.random((3,3))
print(arr)

array of natural numbers  [[0.97628163 0.76445197 0.03864138]
 [0.01907013 0.95236166 0.19668395]
 [0.29856056 0.62477452 0.34074294]]
[[9 8 5]
 [1 5 1]
 [3 7 5]]
[[0.10256222 0.71165434 0.55268272]
 [0.98550181 0.80586659 0.97012513]
 [0.61521271 0.13729405 0.16648545]]


In [13]:
# THIRD METHOD IS  LINEARLY SEPARABLE 
#np.linspace(start,stop,NO OF number) function is used to create the array of linearly separable numbers
# give the start and stop and the number of numbers you want between the start and stop the number is equally spaced means the distance between the two numbers is same
arr=np.linspace(1,10,5)

arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
#np.eye() function is used to create the identity matrix also called as unit matrix
#np.indentity() function is also used to create the identity matrix
arr=np.eye(3)
print(arr)
arr=np.identity(3)
print(arr)
#create a matrix of 3*3 with diagonal elements as 1 and rest of the elements as 0

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


there are all the methods to create a numpy array 



In [21]:
#Arra attribues
#1. shape
a1=np.arange(12)
print(a1.reshape(3,4))
print("shape is ",a1.shape)

#2. size
print("item size is ",a1.size)

#3. ndim
print("dimension",a1.ndim)

#4. dtype
print("data type is ",a1.dtype)

#5. itemsize
print("item size is",a1.itemsize)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape is  (12,)
item size is  12
dimension 1
data type is  int32
item size is 4


In [24]:
#changing data type of the array
a1=np.arange(12)
print(a1)
print(a1.dtype)
a1=a1.astype(float)

#also change to the int 32 ,int64 and so on 
print(a1.astype(np.int32))
print(a1.dtype)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
int32
[ 0  1  2  3  4  5  6  7  8  9 10 11]
float64


In [11]:
arr

array([2, 3, 5, 6, 3, 6, 4, 4, 3])

In [12]:
np.random.randint(4,10,3)

array([7, 5, 8])